import { MovieItemModel } from './movie-item/movie-item.model';

export const movies: MovieItemModel[] = [
  {
    id: 1,
    name: 'Kill Bill',
    releaseYear: 2003,
    kind: 'slasher',
    rating: 5,
    posterUrl: 'https://st.kp.yandex.net/images/film_iphone/iphone360_2717.jpg',
    director: 'Quentin Tarantino',
    description: 'long text',
    duration: 154,
    cast: 'John Travolta, Uma Thurman',
  },
  {
    id: 2,
    name: 'Kill Bill 2',
    releaseYear: 2004,
    kind: 'slasher',
    rating: 5,
    posterUrl: 'https://st.kp.yandex.net/images/film_iphone/iphone360_47015.jpg',
    director: 'Quentin Tarantino',
    description: 'long text',
    duration: 154,
    cast: 'John Travolta, Uma Thurman',
  },
  {
    id: 3,
    name: 'Kill Bill',
    releaseYear: 2003,
    kind: 'slasher',
    rating: 5,
    posterUrl: 'https://st.kp.yandex.net/images/film_iphone/iphone360_2717.jpg',
    director: 'Quentin Tarantino',
    description: 'long text',
    duration: 154,
    cast: 'John Travolta, Uma Thurman',
  },
  {
    id: 4,
    name: 'Kill Bill 2',
    releaseYear: 2004,
    kind: 'slasher',
    rating: 5,
    posterUrl: 'https://st.kp.yandex.net/images/film_iphone/iphone360_47015.jpg',
    director: 'Quentin Tarantino',
    description: 'long text',
    duration: 154,
    cast: 'John Travolta, Uma Thurman',
  },
  {
    id: 5,
    name: 'Kill Bill',
    releaseYear: 2003,
    kind: 'slasher',
    rating: 5,
    posterUrl: 'https://st.kp.yandex.net/images/film_iphone/iphone360_2717.jpg',
    director: 'Quentin Tarantino',
    description: 'long text',
    duration: 154,
    cast: 'John Travolta, Uma Thurman',
  },
  {
    id: 6,
    name: 'Kill Bill 2',
    releaseYear: 2004,
    kind: 'slasher',
    rating: 5,
    posterUrl: 'https://st.kp.yandex.net/images/film_iphone/iphone360_47015.jpg',
    director: 'Quentin Tarantino',
    description: 'long text',
    duration: 154,
    cast: 'John Travolta, Uma Thurman',
  },
];
